In [2]:
import numpy as np 
import time

In [3]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
# Python Lists vs Numpy Arrays:
# Numpy arrays are faster as compared to python lists as they are optimized in C
# Numpy store data in continous memory blocks
# Built in mathematical functions
# Numpy arrays uses less memory as compared to the python lists

In [5]:
# execution performance
size = 1_000_000

#python list

py_list = list(range(size))
start = time.time()
sq_list=[x**2 for x in py_list]
end =time.time()
print(f"python list time = {end-start} seconds")

# numpy arrays

np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2
end = time.time()
print(f"numpy arrays time = {end-start} seconds")





python list time = 0.188431978225708 seconds
numpy arrays time = 0.004110813140869141 seconds


In [6]:
#memory

import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy arrays size = {np_array.nbytes} bytes")


python list size = 8000056000000 bytes
numpy arrays size = 8000000 bytes


In [7]:
#Creating numpy arrays from lists:-

arr = np.array([10,20,30,40,50])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([10,20,30,40,50,"pranay"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)

[10 20 30 40 50] <class 'numpy.ndarray'> int64 (5,)
['10' '20' '30' '40' '50' 'pranay'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [8]:
# Creating numpy arrays using in-built functions:-

arr1 = np.zeros((2,3)) #prefill
print(arr1,arr1.shape)

arr2 = np.ones((3,2))
print(arr2,arr2.shape)

arr3 = np.full((3,2),50) #prefill with val
print(arr3,arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4,arr4.shape)

arr5 = np.arange(1,101,1)
print(arr5,arr5.shape)

arr6 = np.linspace(1,100,4) #evenly spaced arrays
print(arr6, arr6.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[1. 1.]
 [1. 1.]
 [1. 1.]] (3, 2)
[[50 50]
 [50 50]
 [50 50]] (3, 2)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] (100,)
[  1.  34.  67. 100.] (4,)


In [9]:
#properties

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim) #no of dimensions

float_arr = arr.astype(np.float64) #converting numpy arraysfrom one data type to another
print(float_arr,float_arr.dtype)




(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [10]:
#operations on numpy arrays:-

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape(3,2)
print(reshaped,reshaped.shape)

flattened = arr.flatten() #2D => 1D
print(flattened,flattened.shape)

arr2 = np.array([1,2,3,4,5,6]) #accesing elements using index on 1D numpy arrays
print(arr2[0])
print(arr2[1])
print(arr2[4])


arr3 = np.array([[1,2,8],[4,5,6]])
print(arr3[0][1])
print(arr3[1][2])
print(arr3[1][1])


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
1
2
5
2
6
5


In [11]:
#fancy indexing

arr = np.array([1,2,3,4,5,6])

index = [0,2,4]
print(arr[index])

#boolean indexing

print(arr[arr > 2])
print(arr[arr % 2 == 0])



[1 3 5]
[3 4 5 6]
[2 4 6]


In [12]:
#Slicing

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:9])
print(arr[:9])
print(arr[2:])
print(arr[:])



[2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
#common data types

arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)

arr2 = np.array(["pranay","manish"])
print(arr2,arr2.dtype)

arr3 = np.array([2 + 3j]) #complex numbers
print(arr3,arr3.dtype)

arr4 = np.array(["pranay",{1,2,3},3.14]) #objects
print(arr4,arr4.dtype)

[1 2 3 4 5] int64
['pranay' 'manish'] <U6
[2.+3.j] complex128
['pranay' {1, 2, 3} 3.14] object


In [19]:
# Multi-dimensional arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D,axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D,axis=1)
print(sum_of_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [23]:
#3D arrays

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])  # 2 * 3 * 2
print(arr3D,arr3D.shape)

#indexing

print(arr3D[0,1,1])
print(arr3D[1,1,0])


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9


In [25]:
#vectorization only performed in numpy arrays not in lists 

arr = np.array([1,2,3,4,5,6])

print(arr ** 2)
print(arr + 2)


[ 1  4  9 16 25 36]
[3 4 5 6 7 8]


In [27]:
#normalize

arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_deviation = np.std(arr)

print(mean)
print(std_deviation)


normalized_arr = (arr-mean) / std_deviation
print(normalized_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [33]:
# mathematical functions

#aggregation functions:

arr = np.array([1,2,3,4,5,6,7,8])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) # returns the index of the minimum element from the array
print(np.argmax(arr)) # returns the index of the maximum element from the array
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


36
40320
1
8
0
7
4.5
4.5
2.29128784747792
5.25


In [35]:
# power functions

arr = np.array([1,2,3,4])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,2))



[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 1  4  9 16]


In [38]:
# log functions

arr = np.array([1,2,3,4])
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))



[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [45]:
# round

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))

arr = np.array([1,2,3,4,4,2,8,9,2])
print(np.unique(arr))
print(np.sort(arr))

arr2= np.array([1,-2,3,4,-4,2,8,-9,2])
print(np.abs(arr2))





3.0
4.0
3.0
[1 2 3 4 8 9]
[1 2 2 2 3 4 4 8 9]
[1 2 3 4 4 2 8 9 2]
